---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-config
  namespace: dev
spec:
  encryptedData:
    WELCOME_MESSAGE: AgCIWeyJtEfIwCd5ZI7XOwdM4sO4Qvf0uflSlcLwgnxTK1Ktux6MoDfyCuYrI2o/oY6UvgOFwXYr3/09ifC4A9GFTr3ti2u/tU2s2o/XPGsjgycU2emlr4W1CAYPNHpzhfx0cGVGuaMDWiF6JYQdPyqIDjI5TURWcyVHEePsUSwSk2DbUA/a1XNRrufsEwZO5KhP1XXzAtjLSjmW6DYdF9AECts6PcrzS+btrxKM6nRpz5KGLQzFXts+oiPPrebzSB/Ubu1GM2Md8ArMGUw72uUNuHS9ysF4oNYnsSVkzOvRMPZCqpzNPoiegTdJnGhtR3McRjIV9GqTquOud5/4h40Uo9YOthJNOiDnnRBYN9MfhIns9ro+x1MAjI0kgJZSA0m/ZuzwFvaeXWz8MYa/VBPGpFWv/kaGRK1KE2l1X6xeOsGh1OuGb2fPjDF7Yd89lXrQ2nr4n5ilDIvy1djvUYJivIBig9rJrJdJ9yEw2NRtFZuO+lvxDctqb1V6JbBv1jiI8E02EoCKtMnz7zYXSGSmcFldiWRbGyc3TMsNyKrOTCrdVhjykeTtFJF2dF/VUSRAhe4q0T/G6x3SXB95oTsTv3wqPsYewrFcmoXFghpfw8lRj79fqwQiKegRKtT0JxrMoHMrg6IvdT0piTa7CJm0+L+r2qjZOCTJfoahqIOu1F2SfmKrGAo/iOUTVKksV3otD7ch6csG89TKtodWr6rF7upxvt5V9Jl1vQ==
  template:
    metadata:
      creationTimestamp: null
      name: app-config
      namespace: dev
