---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-app-secret
  namespace: default
spec:
  encryptedData:
    api-key: AgBuGxf6xQ0b6dP3mWQQm/GJvljgfV1USqbakdOlGlHRzm4cyevO/o0ajr7vF6gmZa1DceFbYpP9no/mdjIj1gHc/S6QHzOmObmuYr5vB0syQSqQtzoU4+5OPqMleP7Ab8W0n2b5o6Cx2OhU5Bo+PROxaz+d59e2LpA8YR1TGWBln6aKDCko+UyKg9UBLysfMZNMyABc7hwNcufzSKVk2ogr/FuC/vdINwKkUB6ddh/oU40K2R5gNdtbTYyTowurJwup3CSACbY6VXMKY4R/zpsLthPBVOolZVURYza7OBK2N+bbiO4XquzpwDcoYnclATQnD8xbbU+Jqhzy07dUggFXYYvr5SAPZr8/KpFhZM4tyGgD03LpWYt9VuY75aIf0B0zTRe52Lo872KySDPxOgU/TXJBGuRSNwsO7QaxAGBRHOvsJ+8nHwdjHeSSKNT/2ikubI5lHPpaY8XC1QvgY/KgALZ3Nyw7QS76Yw8W+GRLVgcCmbdRpoTuUCwIXhcQxn/hMecQu8yu26VoaijWVqAzjqZJzLHSisJBRTWSgrPR0sPlWSLhVN3wRf1MgWPrNHcsgRODz2W7UYx02ReuPUIPG5ywedn+38Q5lsQ6wO0UXecxNA+FlNbgAdj352z1iChuLXTcU1kRwav/QxE3Nt5zX2nCFFSJux9IwM/q4o6BsBoxnOreFs8rNWnlWEvoRy7g/ZBRed5xXlTmt07JKrda
    database-password: AgB3TEDzHrg/9hbV6/JRR9buOddbgZKeu2YYWirEu4Kex10Rri2JfAF92PTRJEc8NCSDIpLMp8113Hm9VmWyXe3WYydXlO3eQQ3gpdvxyUfv/ASyUzCKBnDyFpRxaaRyrMu14+0Htl//yJfBe3aFT2kXliXoGmHzrIUbUxLUmTm02f/PsDiQzdYuU6xpxuiqInG2RAnLYKi7eCTW0709VJtemNhMB+ZbHtLZY1i8RA2zhrjHn/x0wmJxml3mh4PLaXuAUC5gNho7Ce8HALgI2gHTeG/OZNNnfDsBcEr7m+uIx0mxry+RSmf2RNDD0kYK7+x7gg7sFTMQVkBNslm6tLxQjoXadp/MqYknkzQEhlozdR1FS33HX9OHdgLjDlRb2YUyabPObfSH5CKWunSjffDPKBJY9V5wI0tN37uW4XsSyhmgCpQSz+B9J903esYxEvNsS5dl4VBEb6A8DJb/+BAQ5SgGR7ub5fm8vuVTMQqsQzHlDxuB6GXnw5DlfaXy4s46xd6Z27cHX3CBXRJ6toQaF1ddd3UHzrxPJD+plqQ/sIuGuTKHj4cb5iQ1LdhK0FuqA+SQDAFvNnomemha8w0ssPhr6YF9Tc6yHg0duPvdT/aD4ccAG9zF5fLsEIwx5s3yliiD/U5gMFDDu+Mei9bF5nA6OrxWE8zOye8hPTVSB/l7ZyGI2WYrc+5TjP4eRBWfouGIOihzC+RQg1iBGyiW8C/RO8A=
  template:
    metadata:
      creationTimestamp: null
      name: my-app-secret
      namespace: default
