apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-test
  template:
    metadata:
      labels:
        app: secret-test
    spec:
      containers:
      - name: app
        image: busybox
        command: ['sh', '-c', 'echo "Database Password: $DB_PASSWORD" && echo "API Key: $API_KEY" && sleep 3600']
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: database-password
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: api-key

