name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  DOCKER_IMAGE: whalesnail/customer-docker-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha,prefix=,format=short
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Helm chart values
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "Updating image tag to: ${SHORT_SHA}"
          sed -i "s|tag:.*|tag: \"${SHORT_SHA}\"|g" my-app-chart/values.yaml

      - name: Commit and push changes
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add my-app-chart/values.yaml
            git diff --cached --quiet || git commit -m "Update image tag to ${GITHUB_SHA::7} [skip ci]"
            git push
